### ISSUE TITLE
wonipapa님 그동안 수고하셨습니다.

### ISSUE THREAD

**Issue by donut88** [wonipapa/epg2xml#102]
wonipapa님 그동안 수고하셨습니다.

최근들어 epg소스 사이트들이 자주 업데이트되고

때문에 epg를 불러오지 못하는 현상이 계속 반복되었음에도 불구하고

꾸준히 관리하고 업데이트 해주신 것 정말 감사했습니다.

(다른 곳에 글을 남길 곳이 없어 Issue란에 남김니다.)

**Comment by wonipapa** [comment]
감사합니다.
