### ISSUE TITLE
동일 방송이 1, 2부 나뉜 것 처리

### ISSUE THREAD

**Issue by yunraekim** [wonipapa/epg2xml#18]
요즘 방송사들이 1, 2부로 나눠서 방송하는 것들이 많더군요.
방송사에 따라 "제목 n부" 또는 "제목 (n부)" 형태이니 이 n부 또는 (n부)를 없애고 부제목 맨 앞에 추가하면 녹화 폴더가 깔끔해질 것 같습니다. 재방송을 처리하는 루틴과 유사할 것 같은데 이런 재방송-이건 (재), [재], 스페셜 등-과 부 나뉘는 것을 subject_split_strings 같은 배열로 지정해서 사용자가 추가할 수 있도록 해 주시면 좋을 것 같습니다.

좋은 프로그램 만들어 주셔서 감사합니다~

**Comment by wonipapa** [comment]
제가 이해를 잘 못하겠어서요.
삼국지 1 1부, 삼국지 1 2부 이렇게 되어 있다면 이걸 
제목 : 삼국지1
부제목 : 1부
제목 : 삼국지 1
부제목 : 2부
이런식으로말씀하시는 건지요?
녹화할 시 삼국지1이라는 폴더에 삼국지1-1부, 삼국지1-2부 이렇게 파일이 녹화가 되게하고자 하는 걸로 이해했습니다. 현재는 삼국지1 1부 폴더, 삼국지 1 2부 폴더 이렇게 되리라 예상됩니다.
다음 버전 올리면서 고려해 보겠습니다.

**Comment by yunraekim** [comment]
제 부족한 설명을 잘 이해해 주셔서 감사합니다.
요즘 주말 예능들이 전부 런닝맨 1부/2부 해피선데이 1부/2부 복면가왕 1부/2부 이런 식으로 나뉘어 있어서 말씀하신 그대로 폴더가 나뉘어 버리니 이어보기도 안 되고 불편하더라구요.

**Comment by wonipapa** [comment]
1.2.1 버전에 작업중입니다.
