### ISSUE TITLE
여기 이렇게 쓰는게 맞는건지...?

### ISSUE THREAD

**Issue by pshoewer** [wonipapa/epg2xml#2]
1. Channel.json 에 아래와 같이 추가해보았는데.... 문제가 생기네요...

{"Id":416,"Name":"BTV1","KT Name":"","KTCh":null,"LG Name":"","LGCh":null,"SK Name":"BTV1","SKCh":1,"Icon_url":"http://i.imgur.com/EXtFYQx.png","Source":"SK","ServiceId":326,"Enabled":1},
{"Id":417,"Name":"BTV2","KT Name":"","KTCh":null,"LG Name":"","LGCh":null,"SK Name":"BTV2","SKCh":50,"Icon_url":"http://i.imgur.com/EXtFYQx.png","Source":"SK","ServiceId":325,"Enabled":1}

2. 제목에 회차정보를 포함하는 옵션을 건의 드려봅니다.

**Comment by wonipapa** [comment]
1. 어떤 문제가 생기는 지요?
형식상 문제는 없어 보이는데요. UTF-8 without BOM으로 저장해보시면 될 것 같습니다.

2. 제목에 회차정보라면...
제목 - 회차정보 이런식을 말씀하시는 건가요?
타스의 풀이풀이 사자성어 - 7회
옵션정보로 고려해보도록 하겠습니다.

**Comment by pshoewer** [comment]
1. B사에서 신규 런칭된 SPOTV ON, SPOTV ON2 을 형식에 맞게 넣어서 지금도 이용중입니다.
잘 동작하구요, 그런데 B사 안내채널 1번 50번은 안되드라구요.
아래와 같이 오류 뿜습니다. UTF-8 without BOM 은 확인했습니다.

Traceback (most recent call last):
  File "epg2xml.py", line 543, in <module>
    getEpg()
  File "epg2xml.py", line 92, in getEpg
    GetEPGFromSK(ChannelInfo)
  File "epg2xml.py", line 315, in GetEPGFromSK
    writeProgram(programdata)
  File "epg2xml.py", line 434, in writeProgram
    category = escape(programdata['category'])
  File "/usr/lib/python2.7/xml/sax/saxutils.py", line 32, in escape
    data = data.replace("&", "&amp;")
AttributeError: 'NoneType' object has no attribute 'replace'

2. 회사정보가 제목에 표시되면 직관적이라서 건의 드린겁니다.
- 다만 좀 표시내용이 짧았으면 좋을 것 같습니다.
타스의 풀이풀이 사자성어 - 7회 ==> 타스의 풀이풀이 사자성어(7회)
타스의 풀이풀이 사자성어 (재방송) ==>타스의 풀이풀이 사자성어(7회)(재)
- (재방송)을 옵션 처리하여 보이고 안보이고 가능할까요?

3. Readmo 오탈자 신고
--verobse   ==>  --verbose

정말 덕분에 너무 잘쓰고 있어요.
이렇게 회신 까지 해주셔서 또 너무나 고맙습니다.

**Comment by wonipapa** [comment]
Channel.json 파일에 SPOTV ON, SPOTV ON2를 추가했습니다.
epy2xml 을 1.1.1로 올리면서 안내채널 오류 수정해놓았습니다.

**Comment by wiserain** [comment]
Readme에 BeautifulSoup(b4)도 (bs4)의 오타가 아닌지 글 남겨봅니다.

**Comment by wonipapa** [comment]
오타맞습니다. 수정해야 겠네요.

**Comment by pshoewer** [comment]
EPG GRABER 와 관련하여 문으드릴 사항이 있는데 연락처를 알수 있을까요? 아니면 powerpsh@gmail.com으로 연락 주셔도 고맙겠습니다.
