### ISSUE TITLE
이빨 빠지는 방송 정보 요청합니다.

### ISSUE THREAD

**Issue by wonipapa** [wonipapa/epg2xml#22]
epg2xml 사용하면서 정보가 잘못되거나 가져오지 못하는 채널 정보 알려주세요.
반영하도록 하겠습니다.
SK를 소스로 하는 방송이 아마 많이 빠질 겁니다.

**Comment by smjacksons** [comment]
kt 소상공인방송 정보를 가져오지 못하는 것 같습니다.

**Comment by yunraekim** [comment]
가입해 있는 네이버 카페에 이 문제가 올라왔습니다. 댓글에서 확인된 못 가져오는 채널은 니켈로디언, 매일경제TV, 아리랑TV, 채널J입니다.

**Comment by wowwoo** [comment]
안녕하세요 잘 사용하고 있습니다
SK 신규 채널들 중 인사이트와 인도어스포츠를
추기해 주셨으면 좋겠습니다

함께 추가된 다른 채널들은 타업체에서
서비스 중이던 것이라 Channel.json 수정이
가능한데 저 두채널은 SK만 서비스를 합니다

감사합니다

참 그리고 질문 사항이 있는데요
인수를 SK로 주고 TVheadend에서
네트워크 이름을 사용하는 옵션을 줬을 때
SKName 부분의 이름이 사용되는 것이
아니라 기본 이름이 사용되더라구요

전 3사 모두 나뉘어 있길래 그 이름이
사용되는 것으로 알았거든요

**Comment by wonipapa** [comment]
이건 댓글을 달 수가 없는건지 ... 그냥 쓸께요.
EPG 정보가 돌아가면서 몇개씩 접근이 안되더군요.  오늘은 이게 안되고 다음날은 또 다른게 안되고.

뭔가 조치를 취했는지 모르겠지만 일단 소스를 다른쪽으로 변경할 수 있는 것은 변경할 예정입니다.

몇개 채널이 신규로 추가되었네요. 추가해놓도록 하겠습니다.

그리고 이름은 방송사마다 틀려서 편의상 제 마음대로 정해서 사용중입니다. 방송사 옵션은 가져오는 데이터를 한정하기 위해서 그런겁니다.

원하시는 이름으로 바꾸시려면 epg 셋업 정보에서 원하는 채널만 채널이름을 epg에서 가져오는 게 아닌 걸로 수동으로 하시면 Channel.json 파일 수정안해도 될겁니다.

**Comment by wowwoo** [comment]
답변 감사합니다 이렇게 빨리 답변을 주시다니
좀 감동 ㅠㅜ

**Comment by RiceWorld** [comment]
OCN Series 는 Channel.json 에 아예 빠져있는것 같습니다.
NGC 의 경우 Cahnnel.json 에는 있지만 이빨이 빠지네요.

**Comment by wonipapa** [comment]
OCN 시리즈 작년에 없어졌습니다.
NGC는 Channel.json 파일 변경해서 새로 올렸으니 될겁니다.
SK 소스는 문제가 있다고 판단되어 변경했습니다.

**Comment by wowwoo** [comment]
채널 추가해주셔서 감사합니다 확인해보니 하이라이트TV를 High4K랑 함께 빼신 것 같아요

{"Id":89,"Name":"하이라이트TV","KT Name":"하이라이트TV","KTCh":74,"LG Name":"하이라이트TV","LGCh":91,"SK Name":"Highlight TV","SKCh":42,"Icon_url":"http://i.imgur.com/V9CQ4A6.png","Source":"SK","ServiceId":885,"Enabled":1},

근데 저는 소스가 SK여도 잘 작동합니다 SK 회선이 아닌 곳에서만 문제가 발생하는 것인지...

**Comment by kwonbum** [comment]
잘사용하고 있습니다.감사합니다.

{"Id":112,"Name":"키즈톡톡","
KT Name":"","KTCh":null,"
 LG Name":"키즈톡톡","LGCh":158,"
 SK Name":"","SKCh":null,"
 Icon_url":"http://i.imgur.com/0loInJO.png","Source":"SKY","ServiceId":92,"Enabled":1}

-sk에 없는 채널,source가 SKY인채널이 EPG가 안나옵니다.

-제가 확인한 채널은 UXN,선댄스채널,Discovery HD,Discovery World 정도 입니다.

**Comment by wonipapa** [comment]
SK에 없는 채널이면 SK로 선택시 안나오는게 정상인데요.
소스는 EPG정보를 가져오는 곳이지 시청하시는 IPTV가 아닙니다.
Discovery World도 SK없는 거 아닌지요?

**Comment by wonipapa** [comment]
하이라이트는 소스만 SKY, 서비스아이디는 379로 바꾸시고 넣어주시면 될겁니다.
시간날때 업데이트 해봐야 겠네요.

**Comment by kwonbum** [comment]
제가 애매하게 글을 적었나 보네요.
저는 LG이용하고 있고,LG이용시 Channel.json에 내용중에 sk에 noll로 되어있는 채널 ,source가 SKY인채널 EPG가 안나오고 있습니다.

**Comment by wonipapa** [comment]
제가 LG로 해서 받아봤는데 잘 받아옵니다. 언급하신 채널 모두 xml 파일로 받아서 찾아보면 데이터가 들어 있습니다. putty로 접속해서 epg2xml.py -i LG -o xmltv.xml 로 하신후 xmltv.xml 파일안에서 데이터가 있는지 확인 부탁드립니다.

**Comment by kwonbum** [comment]
epg2xml.php -i LG -l 7 -o lgtepg.xml
로 실행하여 lgtepg.xml확인하면
-<channel id="112">

<display-name>키즈톡톡</display-name>

<display-name>키즈톡톡</display-name>

<display-name>158</display-name>

<display-name>158 키즈톡톡</display-name>

<icon src="http://i.imgur.com/0loInJO.png"/>

</channel>

가 있습니다.

**Comment by wonipapa** [comment]
최신버전으로 쓰고 있는데 그런 문제가 있다면 무료 웹호스팅하는데에 한번 올려놓고 테스트해보시는 건 어떨지 권해봅니다.

**Comment by kwonbum** [comment]
네 감사합니다.

**Comment by ultrastraw** [comment]
채널중 MTN 머니투데이 방송이 "SUPER ACTION" EPG내용이 나옵니다.
skylife 홈페이지에서는 ServiceId를 찾을수가 없네요.(둘다 129로 중복이더라구요)
수정부탁드릴께요

**Comment by wonipapa** [comment]
그러네요. 수정하다가 오류가 있었나 봅니다. 수정하도록 하겠습니다.

**Comment by ultrastraw** [comment]
죄송합니다만, MTN epg serviceId 다시 부탁드립니다.
159번으로 CCTV4 serviceId입니다.
수정부탁드립니다.

**Comment by ultrastraw** [comment]
MBN은 서비스ID는 다른데 EPG정보는 매일경제TV와 같게 나옵니다.
제것이 비정상인지 확실하지는 않습니다.

**Comment by wonipapa** [comment]
MBN 특별한 문제는 없는 것 같습니다.

**Comment by mysoun** [comment]
SK에 키즈톡톡 추가되었습니다. SKB 채널번호 189입니다.
어제부터 SKB에서 어린이TV, 코미디TV만 epg정보를 못가져오네요.
제기준으로 현재 SKB의 채널은 215개가 나오네요.

**Comment by wonipapa** [comment]
SK 반영하도록 할께요.

**Comment by tokn1000** [comment]
선댄스 채널하고 부동산tv 채널이 안나오네여

**Comment by smjacksons** [comment]
KTV, 국회방송, CNTV, FUN TV, edu TV, 부동산TV, tbsTV, BBS불교방송,  BTN불교TV, Good TV, CGNTV, STB상생방송 안나옵니다. 모두 소스가 epg.co.kr인 것 같습니다.

**Comment by wonipapa** [comment]
epg.co.kr 사이트 가져오는 주소가 사라졌습니다. 소스를 바꿔야 할 것 같습니다.

**Comment by wonipapa** [comment]
epg.co.kr 해결 완료했습니다.

**Comment by smjacksons** [comment]
수정된 버전으로 잘 불러와지네요. 감사합니다.
혹시 가능하시면 아리랑 라디오도 추가 가능하실까요? 덕분에 라디오도 편성표 구성해서 잘 쓰고 있습니다.
주소는 http://www.arirang.co.kr/Radio/Radio_Index.asp 입니다.
감사합니다 :)

**Comment by magarinboy** [comment]
수정된 버전 올려주셔서 감사드립니다.
SKB 사용중인데 
"내외경제TV"의 "SK Name" "SKCh"이 빠져 있고,
"Fox life"의 "Source" 값이 오타여서 안나옵니다.

**Comment by wonipapa** [comment]
아리랑라디오는 추가해보겠습니다.
수정된 Channel.json devel 브랜치에 추가했습니다. 다운받으셔도 되고 직접 수정하셔도 됩니다.

**Comment by wowwoo** [comment]
안녕하세요 잘 사용하고 있습니다. 근데 소스가 SKB 인 것들(UMAX, AMC, Life N 등)이 한글이 깨져서 출력됩니다. 현재 무료 웹호스팅 업체를 이용해 epg2xml-web.php로 사용 중입니다. 감사합니다.
![character](https://user-images.githubusercontent.com/29559661/28361504-f342ec74-6cb3-11e7-968c-aaab4645bfcb.png)
](url)

**Comment by yesmbt** [comment]
ubuntu 14.04 server에 올려 사용중입니다. python2.7.13 을 sudo python epg2xml.py명령을 사용합니다.
lguplus 사용
1.2.1으로 올린이후 에러는 없는데 3초 정도면 동작이 종료됩니다. 방송정보는 대략 공중파 4개정도만 당일분을 가져오고 나머진 내일분을 가져옵니다.
1.1.9로 내려서 같은 실행을 해보면 잘 돌아갑니다.

**Comment by wonipapa** [comment]
yesmbt Channel.json 기본 설정이 변겅되어서 그렇습니다. 트래픽 문제등으로 인해서 필요한 정보만 가져오도록 변경했습니다. Enabled값을 1로 변경해주세요

**Comment by wonipapa** [comment]
//wowwoo
저는 문제가 제현되지 않는데요. 확인은 해보겠습니다.

**Comment by wowwoo** [comment]
wonipapa님 일단 소스에서 SKB를 그냥 단순히 SK로 변경했는데 이상없이 잘 정보가 출력됩니다. 시놀로지 웹스테이션에서 돌릴 땐 SKB여도 문제없이 작동합니다. epg2xml.php랑 epg2xml-web.php랑 SKB 소스 부분은 동일하던데 뭐가 문제인지 모르겠습니다. 일단 현재는 그냥 소스를 SK로 변경해서 사용 중입니다. 더불어 Fox life가 출력되지 않아서 이것도 네이버에서 SK로 변경했습니다. 감사합니다 :)

**Comment by zelits** [comment]
epg2xml.py명령을 사용합니다.
qnap ts-212 나스며 엘지유플러스 사용
1.2.1으로 올린이후 방송정보는 대략 공중파 4개정도만 당일분을 가져옵니다.
1.1.9로 내려서 같은 실행을 해보면 잘 돌아갑니다.

**Comment by wonipapa** [comment]
wiki의 faq 읽어보세요
