### ISSUE TITLE
질문 드릴게 있습니다.

### ISSUE THREAD

**Issue by Sinari-O** [wonipapa/epg2xml#29]
-d --display : EPG 정보를 화면으로 보여준다.
-o --outfile : EPG 정보를 파일로 저장한다. ex) -o xmltv.xml
-s --socket  : EPG 정보를 xmltv.sock로 전송한다. ex) -s /var/run/xmltv.sock

세가지 방식의 차이점이나 장단점이 궁금합니다.

epg2xml-web.php , epg2xml.php  의 차이점은 무엇인가요?

**Comment by wonipapa** [comment]
어렵게 생각하실 것 없구요. 설명 그대롭니다
d는 화면 출력해보거나 tvh 내부 그래버로 쓸 때 s는 외부 그래버로 쓸 때 사용합니다.  o는 저장한걸 읽어서 코디에서나 다른 프로그램로 쓰기도 합니다. 코디 이옹해서 tvh 서버 안만들고 쓰기도 하거든요
web 붙은 건 무료 호스팅 서버에 올려놓고 사용하는 겁니다. 나스의 리소스를 분산하는 거죠
안붙은 건 나스에서 쉘 스크립로 작동하는 겁니다

**Comment by wonipapa** [comment]
장단점은 딱히 없습니다. 선호도의 차이라고 할까요.
소켓방식은 크론을 이옹해서 외부에서 가져오는 시간알 정해야 하고 내부 그래버는 파일을 하나 더 설치해야하지난 가뎌오는 시간을 tvh안에서 정합니다.
나스 사양이 안된다면 web버전을 쓰시기를 권합니다

**Comment by Sinari-O** [comment]
감사합니다 궁금증이 풀렸습니다!.

항상 epg 업데이트 햐주셔서 감사히 쓰고 있습니다.

노고에 감사드립니다.
