### ISSUE TITLE
php 로 적용시 line 570 에러

### ISSUE THREAD

**Issue by apple3000** [wonipapa/epg2xml#3]
PHP Fatal error:  Cannot use object of type DOMNodeList as array in /volume1/pvr/wonipapa/epg2xml-1.2/epg2xml.php on line 570

이와 같이 뜹니다.
오늘 다운 받은 파일로 적용해보았습니다. 
로그에는 epg가 제대로 올라오는 것 같아보입니다만.. 위 에러가 있네요.

**Comment by wonipapa** [comment]
테스트 결과 오류가 제현되지 않습니다. 사용 옵션등을 알려주시면 테스트 해보도록 하겠습니다.

**Comment by apple3000** [comment]
php epg2xml.php -i LG -L 1 -o xmltv.xml
PHP Fatal error:  Cannot use object of type DOMNodeList as array in /volume1/pvr/wonipapa/epg2xml/epg2xml.php on line 570

이와 같이 아웃풋 한번 해봤습니다. 
php버전의 문제일가요

**Comment by pshoewer** [comment]
-L을 소문자 -l 로 바꾸어 보세요

php epg2xml.php -i LG -L 1 -o xmltv.xml
==>
php epg2xml.php -i LG -l 1 -o xmltv.xml

**Comment by apple3000** [comment]
대소문자의 상관은 없습니다. 명확히 하고자 대문자를 썼고요. 결과는 동일합니다.
php와 py 로 만들어진 결과물을 비교해보았습니다.

php로 만든(xmltv.xml) 것이 용량이 적습니다. 아래 그림을 봤을때도 어느 라인부터 더 생성안된것으로 파악됩니다.

php로 생성한것도 동일하게  name=egp2xml.py-1.1.5 로 되어있군요.



php로 돌려도 egp2xml.py를 사용한다는 얘기인가요?... 이부분은 그냥 이름만 그런것인지 모르겠습니다.

php로 만들때 display-name 부분이 한줄 더 생기고, python으로 할때는 번호앞에[  ] 가 붙는군요. 이부분이 문제는
아닐듯하고..



결과물
php로 생성한 파일의 끝라인입니다. python은 저부분부터 아래로 더 있습니다.



​

2017-04-06 12:38 GMT+09:00 pshoewer <notifications@github.com>:

**Comment by wonipapa** [comment]
php로 돌려도 egp2xml.py를 사용한다는 얘기인가요?... 이부분은 그냥 이름만 그런것인지 모르겠습니다.
php로 만들때 display-name 부분이 한줄 더 생기고, python으로 할때는 번호앞에[  ] 가 붙는군요. 이부분이 문제는
아닐듯하고..
--------------
파이썬 버전을 PHP 버전으로 바꾸면서 생긴 오타입니다.  다음 버전에서 수정하겠습니다. 그리고 disyplay-name은 PHP 버전쪽에 추가를 하면서 파이썬 버전을 수정하지 않아서 나오는 차이입니다.

저는 에러가 확인되지 않아서 일단 오류나는 소스부분을 에러처리가 되도록 수정하겠습니다. LG 홈페이지에서 가져오는 정보에서 문제가 있는 것으로 생각됩니다. Channel.json파일에서 id 321번 NHK World TV를 disable 한후에도 같은 에러가 나는지 알려주시면 감사하겠습니다.

**Comment by wonipapa** [comment]
추가로 PHP 버전도 알려주시기 바랍니다.

**Comment by apple3000** [comment]
1. 321번 NHK World 제외하고 나니 정상인 것 같습니다.
py 와 php 로 만들때 위 언급했던 displayname 부분때문에 아마도 라인은 더 생기는 듯하지만
처음과 끝의 내용은 동일하게 나오는 것 같습니다.
LG에서 당겨오는 NHK World 채널정보와 php 와의 관계가 문제있나봅니다.
![2017-04-07_9-56-35](https://cloud.githubusercontent.com/assets/14814595/24781266/29989968-1b79-11e7-87a7-ae388f5578ac.png)

![2017-04-07_9-56-54](https://cloud.githubusercontent.com/assets/14814595/24781265/2997f274-1b79-11e7-9d69-f222ba822202.png)

![2017-04-07_9-57-16](https://cloud.githubusercontent.com/assets/14814595/24781267/299a2b8e-1b79-11e7-9223-499ab4a35ebe.png)

2. PHP정보는 다음과 같습니다.
PHP 5.5.33 (cli) (built: Apr 26 2016 16:47:57)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

결과적으로 php버전문제는 아니네요.

**Comment by wonipapa** [comment]
php 5.6.6  버전 이전에 발생하는 에러로 파악되었습니다. 다음 버전에서 수정하도록 하겠습니다
