### ISSUE TITLE
NatGeo Wild 채널 ServiceId 오류 있습니다.

### ISSUE THREAD

**Issue by leesk29** [wonipapa/epg2xml#30]
NatGeo Wild 채널에 NHK WP의 EPG 정보가 나오네요.

Channel.json 파일의 NatGeo Wild 채널  ServiceId는 현재 166 로 설정되어 있습니다.
SKY 홈페이지 편성표에서 찾아보니 NatGeo Wild의 ServiceId가 63으로 나와서 수정하니 정상적으로 표시됩니다.

참고하시고, wonipapa님 epg2xml 너무 편리하게 잘 사용하고 있어 진심으로 감사 인사를 드립니다.
고맙습니다.

**Comment by wonipapa** [comment]
수정하겠습니다. 감사합니다.
