### ISSUE TITLE
EPG 정보를 잘못 받아오는 게 있어서 문의드립니다.

### ISSUE THREAD

**Issue by kumkumi** [wonipapa/epg2xml#31]
LG 사용중입니다.
키즈톡톡이라는 채널이 EPG는 받아오는데, 실제 방송과 내용이 다릅니다.
좀 찾아 보니까 스카이라이프에서 키즈톡톡+ 라는 채널의 편성표가 나오고 있는 거 같네요.
유플러스 홈페이지에서 확인해보니 키즈톡톡은 다른 내용이 나옵니다.
결론적으로, LG에서 나오는 <키즈톡톡>과 스카이라이프의 <키즈톡톡+> 방송이 다른 거 같습니다.
그런데 어디서 정보를 더 찾고 수정해야 하는지 몰라서 요청드려봅니다.

**내용 추가**
어떤 분께서 channel.json 소스를 LG 로 하고 서비스아이디를 805로 해보라고 하셔서 해보니까 되네요.
참고하시면 좋을 거 같습니다.
감사합니다.

**Comment by wonipapa** [comment]
제보 고맙습니다. 수정하도록 하겠습니다.
