### ISSUE TITLE
Plex DVR에서 사용하기 위해 EPG 정보에 영화와 Show를 구분

### ISSUE THREAD

**Issue by dragona79** [wonipapa/epg2xml#34]
이 프로그램을 이용하여 PLEX에 epg 정보를 주고 있는데요..

plex에서 드라마 등을 반복해서 자동으로 녹화 되려면 epg에서 TV 시리즈로 줘야 되는 것 같습니다.

현재는 전부 단편 영화로 녹화가 됩니다.

https://support.plex.tv/hc/en-us/articles/226074728-Setting-Up-Recordings

여길 보시면 epg 정보에 따라 Movie와  Show, News, Sports를 구분 해서 녹화가 가능합니다.

Plex에서 쓰일수 있도록 지원이 가능했으면 좋겠습니다.

**Comment by wonipapa** [comment]
epg 정보에 카테고리가 있지만 원본에 없는 경우가 많아서 힘들지 않을까 봅니다. 기본적으로 제공되는 epg정보가 만히 부정확합니다

**Comment by dragona79** [comment]
회차 정보를 얻어 올수 있는 것 같던데
회차 정보가 있는 것은 영화가 아닌 Show로 처리 하면 되지 않을까요?

**Comment by wonipapa** [comment]
한번 둘러는 보겠지만 너무 기대하지는 마세요.

**Comment by dragona79** [comment]
감사합니다.
