### ISSUE TITLE
v1.2.1 epg 데이터를 이틀치만 가져 와서...

### ISSUE THREAD

**Issue by sanbonguri** [wonipapa/epg2xml#39]
os는 win7-x64, python2.7 입니다.
epg2xml.py v1.2.0p2 까지는 잘 사용했고요, (감솨!!!!)
1.2.1은 epg 데이터를  max 이틀치 까지만 가져오네요.

프로그래밍은 전혀 모릅니다만,,
v1.2.1 epg2xml.py 908라인에서 

        if period > 2 : period = 2

2를 7로 수정하니 3-7일치 까지도 잘 가져오는 것 같아서 임시로 쓰고 있습니다.
다음버전에서는 정상적인 해결책이 나오기를 기대합니다.
수고하세요~

**Comment by wiserain** [comment]
https://github.com/wonipapa/epg2xml/wiki/FAQ#1-%EC%84%A4%EC%B9%98 개발자 분이 의도한 바로 알고 있습니다.

**Comment by wonipapa** [comment]
위키에 적어놓았듯이 이틀치 가져오는 것은 의도한 바입니다.
이전버전과의 호환성 때문에 2이상의 수를 넣어도 2가 되게 한겁니다
