### ISSUE TITLE
not picking episode number for all shows

### ISSUE THREAD

**Issue by yesmbt** [wonipapa/epg2xml#4]
![image](https://cloud.githubusercontent.com/assets/17378909/24949483/b4df5128-1fa8-11e7-97d3-84a00bfbbacc.png)

ex) 웃을을 찿는 사람들 / 4월 12일 uplus 편성표 sbs에는 에피소드 번호가 있는데 epg에서는 보이질 않습니다.

epg2xml.py V 1.1.5

**Comment by wonipapa** [comment]
epg 정보를 가져오는 소스측에서 에피소드 번호를 제공하지 않기 때문에 나오지 않는 것입니다.

**Comment by yesmbt** [comment]
엘지 소스 12일자 http://www.uplus.co.kr/css/chgi/chgi/RetrieveTvSchedule.hpi?chnlCd=504&evntCmpYmd=20170412 링크입니다.


![image](https://cloud.githubusercontent.com/assets/17378909/24990509/7de8d930-204f-11e7-818b-b6347c55c970.png)
![image](https://cloud.githubusercontent.com/assets/17378909/24990513/871f5ede-204f-11e7-9f52-61a87b6d8e45.png)

**Comment by yesmbt** [comment]
늘 선생님 프로그램으로 덕을 보고있습니다. 감사합니다.

xmltv.xml의 아웃풋엔 정확하게 episode번호가 있습니다.
tvheandend의 문제로 보네요.

번거롭게 해드려 죄송합니다.

그리고 감사합니다.

**Comment by yesmbt** [comment]
LG 13일자
http://www.uplus.co.kr/css/chgi/chgi/RetrieveTvSchedule.hpi?chnlCd=502&evntCmpYmd=20170413

![image](https://cloud.githubusercontent.com/assets/17378909/24991581/d78e8b86-2056-11e7-8d90-82a6f4060701.png)

![image](https://cloud.githubusercontent.com/assets/17378909/24991535/6de5f872-2056-11e7-8a77-0c1e84ffc58d.png)

![image](https://cloud.githubusercontent.com/assets/17378909/24991624/3126a976-2057-11e7-9cdc-400addbe4820.png)

**Comment by wonipapa** [comment]
제가 소스에 에피소드 번호가 없다고 한것은 sbs 정보를 가져오는 곳이 uplus가 아니어서 입니다. sbs는 sk브로드 밴드에서
정보를 가져오는데 그 쪽에 에피소드 넘버가 다 있지가 않아서 그렇습니다. uplus 편성표와ㅜ같이 하려면 소스를 LG로 거비스 아이딜
그것에 맞게 변경하시면 될겁니다

2017. 4. 13. 오후 2:41에 "yesmbt" <notifications@github.com>님이 작성:

**Comment by yesmbt** [comment]
아 . .네 Channel.json에 해당 방송은 "Source":"SK"로 설정이 되어 있었습니다.
글 감사드립니다.

제가 어리석어 소스코드를 미리 잘 살피지를 못하고 글을 올려 성가시게 해드려 죄송합니다.

여러모로 프로그램 덕을 많이 보고 있습니다. 
다시한번 감사드립니다.
