### ISSUE TITLE
episode-num 출력방식 옵션(onscreen, xmltv_ns) 적용 요청

### ISSUE THREAD

**Issue by compurator** [wonipapa/epg2xml#40]
Plex Live TV의 EPG 설정시 episode-num의 attribute system 의 값이 onscreen의 경우
모든 정보를 영화로 표현됩니다.
이를 xmltv_ns 로 적용하여 0.10.0/1 의 형태(SeasonNo -1 . EpisodeNo -1, PartNo -1 / TotalPart)로 구성하면
정상적으로 Show 형태로 표현 가능합니다.
Season 처리 방법과 1/2부 분리 등의 추가적인 방법이 필요할 듯 하지만,
불가능할시 episode 정보만(0.10.0/1) 형태로만 되어도 충분할것 같습니다.

**Comment by wonipapa** [comment]
드라마나 예능프로를 관리 목적에 필요하신 것 같아서 글 남기신 것 같습니다.
xmltv.dtd의 xmltv_ns 잠깐 봤습니다. 점으로 시리즈(시즌),  에피소드,  파트 넘버를 구분하네요.
제가 이해한게 맞는지는 모르겠지만
드라마라면 "동이 15회"라면
0.15.0/0
예능이라면 "무한도전 16회 1부"
0.16.1/0
epg 정보상 토탈 파트와 시즌은  첫번째로 처리하면 될 것 같긴 합니다.

에피소드 넘버가 중복으로 들어갈 수 있을 지는 해봐야 할 것 같습니다.

제가 이해한게 틀린게 있으면 글 남겨 주세요.

**Comment by compurator** [comment]
이해하신것이 대부분 맞습니다만,
제가 이해한 것으로는 Season, Episode, Part의 Index는 모두 0부터 시작합니다.
즉 16회의 경우 16-1 한 15가 되어야 16으로 표현 됩니다.

**Comment by wonipapa** [comment]
동이 15회는 0.14.0/0
무한도전 16회 1부는 0.15.0/0
무한도전 16회 2부는 0.15.1/0 이렇게 되야 겠군요.

**Comment by wonipapa** [comment]
devel 브랜치에서 1.2.2 받아서 테스트 해보시면 될 것 같습니다.
1.2.1.에 비교해서 epg2xml.json 파일이 바뀐 부분이 있습니다.
