### ISSUE TITLE
채널 정보

### ISSUE THREAD

**Issue by smjacksons** [wonipapa/epg2xml#46]
안녕하세요. 
pooq에 들어가서 편성표를 확인해보니 예) MBC every1 https://www.pooq.co.kr/player/schedule.html?channelid=M03 편성표 자체가 이틀치 전체 온전히 있는게 아니라서 0시 쯤에 편성표 업데이트 작업을 하면 하루치와 이틀치 새벽분만 파싱이 됩니다. 
또 pooq의 편성표에는 재방송과 부제 정보가 없어서 개인적으로는 예전 소스가 더 나았던 것 같습니다.
JTBC 편성표가 불러와지지 않습니다.

그리고 xmltv_ns 방식으로 바뀐 후로 녹화 파일명에 예전에는 에피소드 넘버만 생성됐던 반면에 지금은
 S01E04 이런 식으로 시즌 넘버가 무조건 붙는데 이를 방지할 수 없는 방법은 없을까요?
감사합니다.

**Comment by wonipapa** [comment]
1. Pooq 편성표를 사용하는 건 부하를 좀 더 분산하고자 하는 의도입니다.
   불편하시면 예비로 남겨두고 예전 소스로 돌아갈 수도 있습니다.
2. xmltv_ns 방식을 plex때문에 도입해달라고 하신 분이 있어서 도입한 것입니다.
   현재는 소스단에서 삭제하는 수밖에 없습니다.
   1.2.3 버전에서 선택가능하도록 해보겠습니다.
