### ISSUE TITLE
Wrong EPG channel information of NATGEO Wild (ID: 137) 

### ISSUE THREAD

**Issue by epitaxy** [wonipapa/epg2xml#50]
epg2xml 유용하게 잘 사용하고 있습니다.

1.2.2 버젼으로 다시 해봤는데도 natgeo wild 채널 ID를 지정해도 읽어오는 정보는 NHK 채널 정보인것 같습니다. 다음판에서는 채널 오류가 수정되었으면 합니다.

미리 감사드립니다.

**Comment by axis95** [comment]
항상 잘 이용하고 있습니다. SBS MTV의 EPG 정보가 오류가 있는것 같습니다.  SBS PLUS와 동일한 EPG가 출력이 됩니다. POOQ에서 불러오는 서비스 ID가 동일한 것 같습니다. 수정해 주시면 감사하겠습니다.

**Comment by wonipapa** [comment]
채널 체크해보겠습니다. 수정된 파일은 https://github.com/wonipapa/Channel.json 과 https://github.com/wonipapa/epg2xml 에 게시하겠습니다.

**Comment by wonipapa** [comment]
수정완료
