### ISSUE TITLE
1.2.2p2 오류

### ISSUE THREAD

**Issue by eastmate** [wonipapa/epg2xml#51]
안녕하세요.

우선 정말 좋은 자료 만들어주셔서 감사하다는 말씀 전합니다.

사용중 오류가 발생하였기에 일단 보고차 작성합니다.

1.2.2p2에서 나오는 증상입니다.

1.2.1에서는 나오지 않았던 오류입니다.(devel 인 1.2.3도 시험삼에 해봤는 데 오류는 나오지 않았습니다.)

현재 tv box gt1과 a95x 이용중이며, 그 중 a95x는 LibreELEC로 이용중입니다.

두 기기 모두 같은 증상을 보였습니다.(python으로 xmltv.xml 이용)

Traceback (most recent call last):
  File "/root/epg/epg2xml.py", line 1152, in <module>
    getEpg()
  File "/root/epg/epg2xml.py", line 136, in getEpg
    GetEPGFromHcn(ChannelInfo)
  File "/root/epg/epg2xml.py", line 594, in GetEPGFromHcn
    startTime = str(day) + ' ' + row.find('span', {'class':'progTime'}).text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

일단 해당 HCN부분을 주석처리하였더니 업데이트는 완료가 되긴합니다만, 

혹시 해결 방법이 있을까요?

**Comment by donut88** [comment]
저도 같은증상 발생하고 있습니다.
내부epg grabber / 외부 XMLTV 모두 동일증상 발생합니다.
확인부탁드립니다.

(ps.항상 감사드려요 ㅎ)

**Comment by wonipapa** [comment]
master에서 1.2.2p3로 받으시면 될겁니다.
1.2.3버전 만들면서 1.2.2에 고치는 걸 잊어버렸네요.

**Comment by eastmate** [comment]
감사합니다~
