### ISSUE TITLE
기능 요청: 부 표기 변환 옵션

### ISSUE THREAD

**Issue by yunraekim** [wonipapa/epg2xml#52]
1부, 2부를 나눠서 서브타이틀로 넣어주신 덕분에 녹화 프로필이 깔끔해졌습니다. 감사합니다.
이왕 문자열을 나눈다면 1부, 2부를 pt1, pt2, CD1, CD2 등으로 변환하는 옵션을 제공해 주시면 좋겠습니다.
https://support.plex.tv/hc/en-us/articles/200265006-Naming-Multi-File-TV-Show-Episodes
위에서 보실 수 있듯이 여러 개로 구성된 에피소드 파일을 표기하는 방법입니다. 

플렉스 다음 에이전트는 타이틀.pt1.날짜 형태의 파일을 잘 인식하여 회차 정보를 매칭시킵니다.
개인적으로 소스를 수정해서 1부, 2부를 pt1, p2로 바꿔서 쓰고 있지만 플렉스나 Kodi를 사용하는 사람들이 많아지면 이 옵션이 매우 유용하리라 생각합니다.

**Comment by reirey** [comment]
tvh의 recording 프로파일에서 저장경로를 "$t.pt$s.$x" 와 같은 형식을 하시면 
"제목.pt1부.mkv" "제목.pt2부.mkv" 와 같은 형식으로 저장되며 이렇게 된 파일명도 plex에서 잘 인식이 됩니다. 

문제는 plex에서 분할된 파일은 몇몇 부분에서 오동작 혹은 기능 지원이 되지 않습니다. 
sync 기능이 대표적으로 분할된 파일을 지원하지 않고 불과 얼마전까지 ios 버전에서는 제대로 이어서 재생이 안되던 버그도 있었습니다. 

차라리 1부, 2부 형식은 1개 EPG로 합치는 옵션을 제공해주시면 좋을 것 같습니다.

**Comment by yunraekim** [comment]
한글이 구분 문자가 될지 모른다 생각하고 처음에 그렇게 설정했습니다만, 분할된 파일로 인식이 되지 않더군요. '1'과 '부' 사이에 공백이나 구분 기호가 필요했습니다. 

생각 못 했는데 1개 정보로 합치는 것이 가능하다면, 그 옵션이 최선일 것 같습니다.

**Comment by wonipapa** [comment]
제가 플랙스를 쓰지 않아서 이해를 제대로 했는지 모르겠습니다만.
yunraekim님에 처음에 쓰신 글은 1부, 2부를 pt1, pt2로 할 수 있는 옵션을 해달라고 하신 것으로 이해를 했습니다.
reirey님의1부, 2부 형식을 1개 EPG로 합친다는게 제가 잘 이해를 못하겠네요.
이개 1부, 2부가 들어간게 요새 예능 프로그램이 1부, 2부로 나눠서 편성표를 하기 때문에 녹화시에 문제가 생겨서 이렇게 했는데 한개로 합친다는 것은 아래와 같은 편성표를
7시시작 8시 종료 무한도전 1부
8시시작 9시 종료 무한도전 2부
7시시작 9시 종료 무한도전으로 하는 것으로 말하시는 것 같습니다.
이게 가능할지는 모르겠네요.

**Comment by reirey** [comment]
wonipapa 님, 만들어주신 EPG 정말 잘 쓰고 있습니다. 다시 한번 감사드립니다. 

이해하신대로가 맞습니다. 
녹화시 방송이 짤리는 경우가 있어 보통 녹화 전후 5분 정도 넉넉히 잡아두는데 
1부, 2부로 나누어진 방송은 중간에 겹치는 부분이 생겨서 연속 시청하기 좀 불편합니다. 
그렇다고 안넣자니 종종 뒷부분이나 앞부분이 짤리기도 하구요.

예전에 어떤 분이 올려주신 스크립트인데 참고하시면 좋을 것 같습니다. 
http://freespiritslab.blogspot.kr/2017/05/kodi-tv-epg.html?m=1

**Comment by yunraekim** [comment]
오후에 시간을 내서 다시 테스트해 봤습니다.

불후의 명곡 전설을 노래하다.1부.2017-07-08
불후의 명곡 전설을 노래하다.2부.2017-07-08
위 형태는 Plex에서 한 에피소드의 중복 에피소드로 인식됩니다. 연속 재생이 안 되고 재생버전을 따로 선택해서 재생해야 합니다.

불후의 명곡 전설을 노래하다.CD1.2017-06-17.mkv
불후의 명곡 전설을 노래하다.CD2.2017-06-17.mkv
두 개 파일로 분리된 한 에피소드로 인식되고 재생 시간도 두 파일을 합친 시간으로 표시됩니다.

불후의 명곡 전설을 노래하다.pt1부.2017-06-03.mkv
불후의 명곡 전설을 노래하다.pt2부.2017-06-03.mkv
이 경우 불후의 명곡 전설을 노래하다.pt1부.2017-06-03.mkv 파일만 인식됩니다. 이 형태는 동작에 뭔가 일관성이 없는 것 같습니다.

불후의 명곡 전설을 노래하다.2017-09-16.pt1부.mkv
불후의 명곡 전설을 노래하다.2017-09-16.pt2부.mkv
이 형태가 reirey님이 말씀하신 것처럼 동작합니다. 플렉스 다음 에이전트에서 에디소드 인식도 정확히 되고
재생 시간도 1 시간 49 분으로 올바르게 표시됩니다.
따로 후처리를 하지 않는 경우라면 이 형태를 사용하면 될 것 같습니다. reirey님, 감사합니다 ;-)

@wonipapa 위와 같은 편법(?)이 존재하고 저 역시 후처리 스크립트를 이용해 x부를 CDx로 바꿔서 사용하고 있지만 위 편법은 서브타이틀이 없는 경우에도 'pt'가 표기되기 때문에 깔끔하지 않은 것 같습니다. 다음 번 업데이트 때 관련 정보를 검토하셔서 옵션을 지원해 주시면 좋겠습니다.

좋은 스크립트, 감사하게 사용하고 있습니다. 고맙습니다.

**Comment by wonipapa** [comment]
요청하신 사항 관련해서 몇가지 테스트는 해봤습니다.
1. 부를 pt나 CD등으로 바꾸는 것은 옵션사항에서 주면 될 문제같습니다.
2. EPG 합치는 것도 소스를 조금 많이 바꿔야 하지만 가능하더군요. 문제는 애니메이션 채널같은 경우에 같은 제목으로 몇회를 방영할 때 생기는 하나로 합쳐지는 경우가 생깁니다. 기타 소소한 문제들도 있구요.

고민은 좀 해보겠습니다.
