### ISSUE TITLE
수정 요청 : EBS2 서비스아이디 수정 부탁드립니다.

### ISSUE THREAD

**Issue by jjh79** [wonipapa/epg2xml#53]
오늘  EPG를 보다가 다른 정보가 나와 확인해 보니 E07로 변경된것 같습니다. 
확인 부탁드립니다.

정말 편리하게 잘 사용하고 있습니다. 감사합니다.

**Comment by wonipapa** [comment]
연휴끝나고 처리하도록 하겠습니다.
