### ISSUE TITLE
epg정보 부분 못가져오는 현상

### ISSUE THREAD

**Issue by infofun** [wonipapa/epg2xml#54]
확인 결과 소스부분 Channel.json파일에 source 부분이 SKY인 kbs2 등 못가져오는거 같아요
다른 분들은 잘 가져와지나요?

**Comment by hsofficial** [comment]
저도 약 3일전쯤 Channel.json 몆몆채널 더 enabled한 이후 주요 채널들에 대해서 정보 업데이트가 안되고있네요. 혹시나 실수인가 싶어서 tvheadend에서 epg grabber을 모조리 삭제하고 다시 정보 업데이트를 해봐도 마찬가지구요. grabber 자체는 제대로 인식이 되고 있습니다. 참고로 주변에 nas 이용하시는분들 몆분도 비슷한 일을 겪고 계시더라구요

**Comment by hsofficial** [comment]
참고로 인식이 안되는 채널들중에 JTBC,tvN처럼 자주 예약녹화를 하는 채널들이 포함된지라 상당히 당혹스러웠습니다. 그리고 꼭 SKY쪽 소스 한정의 문제만은 아닌거같구요. 같은 증상 경험하시는분들 상세하게 comment 해주세요

**Comment by infofun** [comment]
https://www.skylife.co.kr/channel/epg/channelChart.do
실시간 편성표 보니깐 해당정보에 프로그램 정보가 없다고 나오네요
스카이라이프에서 정보 제공이 안되고 있는거 같아요.

**Comment by donut88** [comment]
실시간 편성표에 따르면 월요일에서 화요일넘어가는 자정부터 epg정보 다시 나오는거 같아요

**Comment by hsofficial** [comment]
네 소스들이 많이 돌아왔네요 그럼에도 아직 정상적으로 정보업데이트가 안되는 채널들이 간헐적으로 있습니다. 가령 오늘 SBS같은 경우는 하루종일 야구만 튼게 아닌데 자정즈음에 업데이트이후 편성표 열어보니까 야구경기 편성 하나만 정보가 업데이트되어있더라구요.

**Comment by donut88** [comment]
sky소스는 전부 돌아왔고
kt소스는 안돌아오네요
수정이 필요해 보입니다ㅎ

**Comment by wonipapa** [comment]
SKY 소스 담당자가 추석연휴동안 빼먹은 것 같네요. 일시적인 해프닝일 것 같습니다.
KT 부분은 소스 자체를 변경해야 해서 좀 시간이 걸릴 듯합니다.
