### ISSUE TITLE
SK 기준으로 안나오는 채널보고

### ISSUE THREAD

**Issue by wlwhfhs** [wonipapa/epg2xml#58]
현재 epg2xml 1.2.3p2 (이제 히스토리 채널 잘 작동됩니다.) 
SK 기준으로 안나오는 채널 적어 봅니다.(혹시라도 수정에 도움되실까 싶어서...)

아임쇼핑  ID: 265
신세계쇼핑  ID: 260
K쇼핑  ID: 119
GS MY SHOP ID:  84
현대홈쇼핑+샵  ID: 313
쇼핑엔티  ID:  258
W 쇼핑  ID: 213
NS Shop+ ID: 143
마이펫TV ID: 240
Asia N ID:  8
B Shopping ID: 11---> 방송정보는 잘 받아오나 sk채널이 빠져있음  
Golf Channel Korea ID: 200
토마토TV ID: 297
이데일리TV ID: 272
YTN 라이프 ID: 220
CNN US ID: 47
Bloomberg TV ID: 21
내외경제TV ID: 225----> SK채널 164번으로 있습니다.--->추가필요. 방송정보도 못 받아옴.
플레이런TV ID: 457
9colors ID: 1
Arte TV ID:  6
i-Concerts ID : 94
FISHING TV ID: 72
ONT ID: 156
폴라리스TV ID: 302
리얼TV ID: 160
tbsTV ID: 198

쭉 적다보니 sk채널번호 순이라서 ID순서가 아니라서 번거로울듯 하네요. 죄송합니다.
잘 사용하고 있고 다른분들을 위해 공유해 주셔서 감사합니다. 늘 행복하세요!!

**Comment by wonipapa** [comment]
sk url이 변경되었네요. 낼 반영하겠습니다

**Comment by eastmate** [comment]
SK기준으로 최근 변경점은..
헝그리앱TV, Tvis 삭제

History HD가 History로 변경
Food TV가 Lifetime로 변경
정철영어TV가 플레이런TV으로 변경

롯데원티비 추가
다큐원 추가

등인데, 이미 wonipapa님께서 반영해주셨구요.
최근 추가된 BET 채널만 적용이 안되어 있네요.(239번 SKB 기준 ID 788)

좋은 자료 항상 감사히 잘 쓰고 있습니다. 감사합니다.

**Comment by wlwhfhs** [comment]
@eastmate  변경점을 일목요연하게 정리해 주신 덕분에 m3u파일 수정할 수 있었습니다,
감사합니다. 살펴보니 헝그리앱TV 주소가 현재는 다큐원 주소가 되었더군요. 

B shopping은 다른 타 경쟁사 IPTV사에는 있는데 왜 자사인 SK에선 방송 송출목록에 안한다고 
나와있는지 의문입니다. 주소는 udp://@239.192.67.36:49220 입니다. 제가 예전에 m3u파일 등록시 114번으로 임의등록 했었나 봅니다. (채널주소는 다른분의 언급이 있을시 삭제토록 하겠습니다.)

덕분에 BET채널도 알게 되었네요. 감사합니다.

**Comment by wonipapa** [comment]
반영완료
