### ISSUE TITLE
채널 번호

### ISSUE THREAD

**Issue by smjacksons** [wonipapa/epg2xml#6]
Epg Grabber Channels에서 채널 번호가 Number가 아닌 Names로 갑니다.
Number는 0으로 되어 있고 "Asia UHD","109","109 Asia UHD" 이런 식입니다.

**Comment by smjacksons** [comment]
KT 홈페이지보니 채널이 종료되는군요. ㅠㅠ
프로그램 항상 잘 쓰고 있습니다.

**Comment by wonipapa** [comment]
무슨 뜻인지 잘 이해를 못하겠습니다. 출력부분을 첨부해주시면 참고하겠습니다.

**Comment by smjacksons** [comment]
http://i.imgur.com/HSneUhK.jpg
보시면 9color의 채널 번호는 163번 입니다. Number에 채널 번호가 가야 하는데 Names로 모두 가있습니다.

**Comment by wonipapa** [comment]
이해했습니다.
xmltv 설정에서 실제 티비 채널 번호를 나타낼 방법이 없습니다. 채널 번호를 넣으려면 Name에 넣은 수 밖에 없습니다.
Names에 들어가 있는 채널 번호를 tvheadend가 사용이 가능한 것으로 알고 있습니다.

**Comment by smjacksons** [comment]
epg grabber modules의 xmltv 설정칸에서 channel numbers에 체크하면 채널번호를 인식하네요. 감사합니다 :)

**Comment by smjacksons** [comment]
혹시 한 가지 건의드려도 될까요? 
Channel.json 파일에서 제가 사용하지 않는 채널들은 0으로 두어서 비활성화하는데 channel.json 파일이 수시로 업데이트 되기 때문에 업데이트 시에 일일이 수동으로 다시 disable 해줘야 하는 번거로움이 있습니다. 그래서 혹시 업데이트 시에 이전 파일과 Enabled 부분을 비교해서 자동으로 반영해주는 updater가 있었으면 좋을 것 같다는 생각이 듭니다. 
조금 무리한 건의드린 거 아닌가 하는 생각이 드네요. 한번 고려해 주시면 감사하겠습니다. :)

**Comment by wonipapa** [comment]
프로그램 실력이 미숙해서 가능할 지는 모르겠지만 한번 검토는 해보겠습니다.
