### ISSUE TITLE
POOQ를 이용하는 채널정보가 표시되지 않습니다.

### ISSUE THREAD

**Issue by frinne** [wonipapa/epg2xml#62]
안녕하세요.

 POOQ를 이용하는 채널의 EPG정보가 표시되지 않습니다. (JTBC, MBC MUSIC 등)
SKY를 이용하는 채널은 표시가 되어서 SERVICE 만 SKY로 변경하였더니 정보를 가져오지 못하는데
각 채널의 SKY의 service id 를 알수 있는 방법이 있는지요?

감사합니다.

**Comment by wonipapa** [comment]
https://m.clien.net/service/board/cm_nas/11267857
이글의 1a2a3a4a님 글 참조해서 해보세요

**Comment by frinne** [comment]
늘 감사드립니다.
