### ISSUE TITLE
이터레이션 도중 멈춤현상

### ISSUE THREAD

**Issue by zextor** [wonipapa/epg2xml#64]
안녕하세요.
먼저 epg2xml 모듈 제작에 감사드립니다.
다름이 아니라 이번에 우분투서버를 새로 들이면서 적용을 하고 있는데요.
아래와 같이 이터레이션도중에 그냥 멈춰 버리네요.

`zextor@ubuntu:~$ python epg2xml.py`
`Traceback (most recent call last):`
`  File "epg2xml.py", line 1216, in <module>`
`    getEpg()`
`  File "epg2xml.py", line 132, in getEpg`
`    GetEPGFromPooq(ChannelInfo)`
`  File "epg2xml.py", line 659, in GetEPGFromPooq`
`    epgzip(epginfo)`
`  File "epg2xml.py", line 957, in epgzip`
`    epg1 = next(epginfo)`
`StopIteration`
`zextor@ubuntu:~$`

이런경우 어떤것이 원인일까요
감사합니다.

**Comment by wonipapa** [comment]
체크해보겠습니다.  추가적으로 파이썬 버전을 알려주시면 좀 더 도움이 됩니다.

**Comment by zextor** [comment]
안녕하세요. 파이선 버전을 같이 남깁니다.

Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2

**Comment by wonipapa** [comment]
사이트에 문제가 있거나 해서 나타나난 오류 같습니다.  에러처리 루틴이 필요한 것 같습니다.

**Comment by minky099** [comment]
저도 같은 현상이네요ㅜㅜ

Traceback (most recent call last):
  File "/home/hts/.hts/tvheadend/epggrab/epg2xml.py", line 1221, in <module>
    getEpg()
  File "/home/hts/.hts/tvheadend/epggrab/epg2xml.py", line 135, in getEpg
    GetEPGFromHcn(ChannelInfo)
  File "/home/hts/.hts/tvheadend/epggrab/epg2xml.py", line 614, in GetEPGFromHcn
    epgzip(epginfo)
  File "/home/hts/.hts/tvheadend/epggrab/epg2xml.py", line 962, in epgzip
    epg1 = next(epginfo)
StopIteration

파이썬 버젼은 2.7.13입니다..

**Comment by wonipapa** [comment]
원인은 파악했습니다.

**Comment by wonipapa** [comment]
1.2.3p4 버전에서 수정했습니다.
