### ISSUE TITLE
안녕하세요?

### ISSUE THREAD

**Issue by kumkumi** [wonipapa/epg2xml#68]
github에 익숙치 않아서 여기다 적는 게 맞는지 모르겠습니다.
다름이 아니고 docker에 tvheadend를 설치해서 사용중인데,
얼마전부터 JTBC, MBN, 채널A, TV조선, 연합뉴스 TV, YTN, SBS Sports, EBS2, MBC MUSIC, SBS MTV 등 
다양한 채널이 EPG가 안 나오고 있습니다.
오늘 좀 시간이 있어서 싹 지우고 docker 재설치부터 해봤는데,
EPG는 여전이 못 받아오네요.
L사 사용중이고 며칠전까지는 잘 되었었는데, 
다시 설치해도 안 되는 거보니 이상이 있는 거 같아 글 남겨봅니다.
검색해보니 다른 분들도 최근에 그런 거 같습니다.

**Comment by dor1a** [comment]
pooq이 문제인것 같습니다.
해당 소스를 바꿔주거나 pooq 부분을 수정 해줘야 할 것 같네요

**Comment by wonipapa** [comment]
소스 수정 중에 Pooq 함수로 분기되는 부분이 삭제되었더군요.
1.2.3p5버전에서 복구 했습니다.
