### ISSUE TITLE
SK, SKY

### ISSUE THREAD

**Issue by dor1a** [wonipapa/epg2xml#71]
SK와 SKY, SKB의 EPG가 아예 안불러집니다.

URL은 괜찮은데 이상하게 안불러지네요.

**Comment by wonipapa** [comment]
확인해보겠습니다.

**Comment by dor1a** [comment]
확인하느라 고생하십니다.
그런데 무슨 문제인지는 몰라도 오늘자 부터 정상적으로 잘 불러오네요.

**Comment by jinguman** [comment]
SK쪽 데이터가 또 안불러와지네요.. 약 삼일전까지는 잘 되었던거 같은데..

**Comment by wonipapa** [comment]
특별한 이상은 없는 것 같습니다. SK쪽 서버가 불안할 수도 있습니다.
