### ISSUE TITLE
아래와 같은 메시지가 나옵니다.

### ISSUE THREAD

**Issue by project21c** [wonipapa/epg2xml#74]
아래와 같은 메시지가 나옵니다. epg가 나오기는 하는데 에러가 나서 궁금합니다.

Traceback (most recent call last):
  File "./epg2xml.py", line 1264, in <module>
    getEpg()
  File "./epg2xml.py", line 128, in getEpg
    GetEPGFromSKB(ChannelInfo)
  File "./epg2xml.py", line 404, in GetEPGFromSKB
    cell = row.find('span', {'class':'title'}).text.decode('string_escape').strip()
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by eastmate** [comment]
이유는 모르겠으나, BET 채널 정보를 받아오지 못해서 그런 걸로 보여집니다.

Channel.json의 458번 BET 채널의 소스를 SKB에서 SK로 수정해주시면 됩니다.

**Comment by project21c** [comment]
친절한 안내 감사드립니다. 바로 수정해서 에러가 나지 않습니다.

**Comment by wonipapa** [comment]
지금 실행해봤는데 에러가 안나와서 이유는 잘 모르겠습니다만 skb html 파일에 오류가 있는 것 같습니다. 문제가 재현되면 테스트 해보겠습니다.
