### ISSUE TITLE
ISCS 정보를 제대로 받아오지 못하는 것 같습니다.

### ISSUE THREAD

**Issue by mogilee** [wonipapa/epg2xml#75]
ISCS EPG정보를 제대로 받아오지 못하는 것 같습니다.

더 정확하게는 2018-01-15 날짜로 EPG를 가져오면, 1월 15일 방송에 대해서는 정보를 받아오지 못하고 1월 16일 이후 정보만 받아오는 것 같습니다.

일단 972라인을

$day = date("Y-m-d", strtotime("+".($k - 2)." days"));

으로 변경하니 정상 동작은 합니다.

**Comment by wonipapa** [comment]
확인후 수정하도록 하겠습니다.
감사합니다.

**Comment by wonipapa** [comment]
생각보다 수정해야할 부분이 좀 많네요. 시간나는데로 수정해놓겠습니다.

**Comment by wonipapa** [comment]
검토해보니 ISCS는 빼는게 날 것 같다는 생각입니다.
같은날에 두날짜의 데이터가 오전 오후로 나오고 마지막 데이터가 다음날 데이터와 겹치는 경우가 생깁니다. 이것 때문에 
대체할 다른 것을 고려해보겠습니다.

**Comment by monsoons** [comment]
자주 녹화하는 채널이 있다보니 수정하려하는데 channel.json 소스부분을 어떻게 수정하면 정상적으로 epg 를 가져올수 있을까요?

**Comment by wonipapa** [comment]
Channel.json 파일 다시 받으세요.

**Comment by monsoons** [comment]
Channel.json ISCS 소스가 변한게 없는거 같은데요.
