### ISSUE TITLE
Error : xmltv.sock 파일을 찾을 수 없습니다.

### ISSUE THREAD

**Issue by dmc31a42** [wonipapa/epg2xml#76]
tvheadend-testing_bromolow-5.2_4.1.2140-1 버전때는 xmltv.sock 에 권한이 없어서 접근할 수 없으면 접근할 수 없다고 오류가 떴는데, 4.4.20171030-1 버전때는 아래와 같이 파일 자체를 찾을 수 없다고 합니다.
파일이 존재하는 것 확인했고, 해당 경로에 root계정으로 접근가능한것도 확인했습니다.
Error :  xmltv.sock 파일을 찾을 수 없습니다.

혹시나해서 직접 root 계정에서 파이선 실행하고 아래와같이 하니까 접속거부라 뜨네요.
sh-4.3$ python
Python 2.7.12 (default, Nov 10 2017, 20:29:25)
[GCC 4.9.3 20150311 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
>>> sock.connect("xmltv.sock")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
>>> quit()

일단은 tv_grab_file로 때우고있습니다만. 가능하시면 확인부탁드립니다.

**Comment by wiserain** [comment]
epg2xml과는 전혀 관련이 없는 문제입니다. tvheadend 버그로 wonipapa님이 할 수 있는게 없을겁니다.

**Comment by wonipapa** [comment]
이건 제가 해결할 수 없는 문제라서 클로즈 시키겠습니다.
