### ISSUE TITLE
KTV 소스 에러(지난 번 BET 채널 에러관련)

### ISSUE THREAD

**Issue by eastmate** [wonipapa/epg2xml#77]
Traceback (most recent call last):
  File "/root/epg/epg2xml.py", line 1264, in <module>
    getEpg()
  File "/root/epg/epg2xml.py", line 128, in getEpg
    GetEPGFromSKB(ChannelInfo)
  File "/root/epg/epg2xml.py", line 404, in GetEPGFromSKB
    cell = row.find('span', {'class':'title'}).text.decode('string_escape').strip()
AttributeError: 'NoneType' object has no attribute 'text'

지난 번 BET 채널과 같은 에러메세지가 나와서 올려봅니다.
https://github.com/wonipapa/epg2xml/issues/74

KTV 소스를 SKB로 했더니 위와 같은 에러메세지가 나왔습니다.

BET과 같은 경우인지는 알 수 없으나, 일단 지난 번에 보지 못하셨다고 하셔서 올려봅니다.

참고로 SK로 하면 에러없이 잘 됩니다.

항상 잘쓰고 있습니다. 노고에 감사드립니다.

**Comment by wonipapa** [comment]
소스를 보니 데이터가 제대로 안들어 가 있을 때 나오는 오류 같네요.
수정해보도록 하겠습니다.

**Comment by eastmate** [comment]
오늘 확인해보니까 BET 채널도 같은 증상이 있는 것 같습니다.(7일치)

BET 채널 이상이기에 다시 한번 보고드립니다.

SKB로는 안되고 SK로는 됩니다.

감사합니다.

**Comment by wonipapa** [comment]
문제점을 일단 찾아서 패치했습니다. SK쪽도 에러가 나는지는 지금 봤네요.
체크해보도록 하겠습니다.

**Comment by eastmate** [comment]
살펴보니 현재 SkyDrama 쪽은 문제가 사라진 상태로 보여집니다.

바쁘신 와중에 항상 감사합니다. (__)

**Comment by wonipapa** [comment]
수정 완료

**Comment by eastmate** [comment]
감사합니다!
