### ISSUE TITLE
php 버전에 대한 문의

### ISSUE THREAD

**Issue by wiserain** [wonipapa/epg2xml#8]
php 버전이 좀 더 용량이 작고 효율적이지 않나 싶어서 전환을 고려하고 있습니다. docker container 내에서 테스트 하였으며 container 환경은 alpine linux / php7 입니다. 명령어는 대략

```
$ php7 -f epg2xml.php
```

입니다. 질문 드리고 싶은 내용은,

1\. <del>용량의 차이가 발생합니다. 결과물인 xml 파일을 compare를 해보니 python 버전 대비 누락되는 부분이 있는데 어떤 부분을 점검해보면 될까요? php 모듈 중에 dependency가 있다면 알려주시면 감사하겠습니다. </del>

해결했습니다. php7 php7-json php7-dom php7-mbstring php7-openssl로 해결되었습니다. 마지막 php7-openssl이 문제였습니다.

2\. 다음과 같은 경고 메시지가 발생합니다. 
```
PHP Notice:  Undefined offset: 3 in /epg2xml/epg2xml.php on line 537
```
굉장히 많은 부분에서 발생하는데 <del>1의 원인이 될 가능성이 있을까요?</del> 원인이 뭘까요?

3\. python 버전에서는 커맨드라인 옵션이 가능한데 php 버전에서도 json 옵션을 override할 방법이 있을까요?

감사합니다.

**Comment by wonipapa** [comment]
1번의 PHP 모듈은 은 시놀로지 기본으로 설정되어 있는 상황이라서 특별히 확인하지 않았습니다.
PHP 배포판마다 기본에 포함하지 않는 경우가 있는 것 같네요.
openssl은 PHP가 외부에서 파일을 불러올때 https로 되어 있으면 기본적으로 불러오지 못합니다. 그래서 필요한 모듈입니다. 필요모듈에 관해서 명시해놓도록 해놔야 겠네요.

2번은 소스를 들여다봐야 대답할 수 있는 문제 같아서 검토후 다시 글 달도록 하겠습니다.

3번은 python 버전과 동일하게 처리하시면 됩니다.

**Comment by wonipapa** [comment]
2번 사항은 저에게는 발생하지 않아서 확실하게 말씀드릴 수는 없지만 정규표현식으로 방송정보를 분리할 때 발생하는 문제같습니다. 배열에서 값이 없어서 생기는 문제로 에러처리를 하면 해결될 것 같습니다.

**Comment by wonipapa** [comment]
시놀로지에서는 error를 리포팅하지 않는게 기본설정으로 되어 있어서 2번의 오류를 제가 보지 못했네요. 문제를 확인했습니다.

**Comment by wiserain** [comment]
1번의 경우 php 관련 패키지를 모두 설치할 수도 있지만, docker 이미지를 빌드하는 과정에서 용량을 최소화하려고 하다 보니 생긴 고민이었습니다. 혹시 비슷한 고민이 필요하신 분들은 참고하셨으면 좋겠네요.

2번은 구글링해보면 빈번하게 나타나는 warning인데 잘 모르겠네요 critical하지는 않습니다. 결과가 python 버전과 동일하거든요. 확인하셨다니 더 개선될 수 있으면 좋겠네요.

3번은 확인했습니다. 사실 사용방법에 대한 질문에 가까웠는데

```
php7 -f epg2xml.php -- -d -i {KT,SK,LG}
```

이런 식으로 옵션을 넣어주니 잘 됩니다. 한가지 사소한 오타는 epg2xml.php 파일 안에 epg2xml.py가 언급됩니다. 26번째 라인 근처입니다.

잘 사용하고 있고 답변 고맙습니다.

**Comment by wonipapa** [comment]
2번문제는 소스를 고치지 않는다는 가정하에서 
error_reporting(0);
만 상단에 추가하면 쉽게 해결될 문제이긴 합니다. 물론 근본적인 해결방법은 아닙니다.

**Comment by wiserain** [comment]
Notice에 대한 에러만 없애는 것이 추후 대응에 더 낫지 않을까요? ```error_reporting(E_ALL ^ E_NOTICE);```

**Comment by wonipapa** [comment]
일단 버전 변경없이 error_reporting(0); 만 추가해놨습니다.

1.1.9 버전에서 에러가 나오지 않도록 수정해보겠습니다. 대충 수정가닥은 잡았고 테스트 좀 더 해보고 올려놓도록 하겠습니다.
파이썬 버전은 수정할게 없어서 버전 넘버를 어떻게 해야 할지 고민이긴 하네요. 버전 올리려면 뭐라도 추가해야 겠습니다.

그리고 에러나오게 하는것은 그렇게 해도 될 것 같긴 합니다.

**Comment by wiserain** [comment]
처음의 고민에 대한 답을 마지막으로 남겨놓자면, php 버전이 약간 용량이 작고 (docker compressed image 기준 94MB vs 91MB) 스크립트 실행 시간 기준으로 속도는 약간 느리네요. 결국 편의성 및 접근성 말고는 대동소이하네요.
