### ISSUE TITLE
바뀌거나 추가된 채널 로고 3개

### ISSUE THREAD

**Issue by wowwoo** [wonipapa/epg2xml#85]
안녕하세요

SK stoa                   http://i.imgur.com/YsVeqhU.png
XtvN                       http://i.imgur.com/6NUlFGD.png
스크린 골프존        http://i.imgur.com/Yc5aNeb.png

추가해주신 channel.json에 위의 로고들이 반영되길 기다리다
그냥 만들어주신 포맷대로 만들어 봤습니다
(설마 벌써 반영되었는데 저만 모르는 그런)

언제나 감사합니다

**Comment by wonipapa** [comment]
제가 요새 업무가 바빠서 추가를 못했습니다.
다음 주말에는 좀 한가해지지 그때 반영하도록 하겠습니다.
감사합니다.

**Comment by wlwhfhs** [comment]
@wowwoo 감사합니다. epg에 조만간 추가가 되겠네요. 추가된 채널중에 
신기한나라tv도 있습니다. http://www.kidsland.tv/ 이것도 만들어 주셔야 할듯...
개선해 주셔서 감사합니다.

**Comment by wonipapa** [comment]
로고 보내주신 것 과 신규 로고 등 수정사항 반영했습니다.
