### ISSUE TITLE
SKB 소스 오류

### ISSUE THREAD

**Issue by magarinboy** [wonipapa/epg2xml#86]
XMLTV SOCKET 으로 장비 하나는 PHP CLI 사용중이고

한대는 PHP WEB 으로 사용중입니다.

이틀전부터 SKB 소스만 못가져오네요. 

에러 메세지는 안나옵니다.

**Comment by wonipapa** [comment]
2월중까지는 제가 업무 관계로 3월 정도에 수정하도록 해보겠습니다.
제보 감사합니다.

**Comment by wonipapa** [comment]
수정 완료
