### ISSUE TITLE
인코딩 관련

### ISSUE THREAD

**Issue by dor1a** [wonipapa/epg2xml#89]
바쁘신와중에도 시간내서 SK 소스 수정하시느라 고생하셨습니다.

쓰는입장에서는 감사한 마음밖에 없네요.

이번에 1.2.5 버전 업데이트 되면서 인코딩이 이상하게 올라오길래 1.2.4p1과 비교해보니 다음과 같은 부분이 빠지며 인코딩에 이상이 생기더군요.
$response = mb_convert_encoding($response, "UTF-8", "EUC-KR");

해당 부분을 추가하니 인코딩이 정상적으로 돌아왔습니다.

**Comment by wonipapa** [comment]
음 제 환경에서는 테스트할 때는 그 부분 때문에 문제가 있어서 뺀건데 다른 환경에서도 테스트 해봐야겠네요

**Comment by sysilion** [comment]
안녕하세요. 인코딩관련문제 하나 더 있는거 같아서 새로 이슈 안만들고 여기다 댓글로 남깁니다.

현재 Windows 상에서 python 2.7.13 쓰고있구요, master 코드 clone 해서 설정 바꾸지 않고 python epg2xml.py 실행 했습니다.

```
...
      <actor>제니퍼 코넬리</actor>
      <producer>론 하워드</producer>
    </credits>
    <category lang="kr">영화</category>
    <category lang="en">Movie / Drama</category>
    <rating system="KMRB">
      <value>15???댁긽 愿?뚭?</value>Traceback (most recent call last):
  File "epg2xml.py", line 1268, in <module>
    getEpg()
  File "epg2xml.py", line 130, in getEpg
    GetEPGFromSKY(ChannelInfo)
  File "epg2xml.py", line 474, in GetEPGFromSKY
    writeProgram(programdata)
  File "epg2xml.py", line 1101, in writeProgram
    print('      <value>%s</value>' % (rating))
IOError: [Errno 0] Error
```

잘 출력이 되다가 가끔씩 에러가 발생하는 것 같네요.

근데 이부분을 파일 출력으로 설정 바꾸면 정상동작 합니다.

음.... 그래서 잘 쓰고는 있습니다. ^^

시간이 남으신다면 관련문제도 확인 부탁드립니다. :D

**Comment by wonipapa** [comment]
SKB 함수 관련 인코딩 수정 및 rating 오류 수정했습니다.
/syilion님 문제가 일어나는 채널 알려주시면 테스트 해보겠습니다.
