### ISSUE TITLE
uplus 디스커버리 아시아

### ISSUE THREAD

**Issue by ahas00** [wonipapa/epg2xml#90]
유플러스에 있는 디스커버리 아시아는 정보를 아예 받아오질 못하는것 같습니다. 
제가 문제가 있는건지 처음부터 계속 되질 않더군요 번거로우시겠지만 확인좀 부탁드립니다.

**Comment by wonipapa** [comment]
sky에서 채널이 없어져서 소스를 변경했습니다.

**Comment by ahas00** [comment]
감사합니다
