### ISSUE TITLE
프로그램 제목의 "<", ">" 문자 문제

### ISSUE THREAD

**Issue by sixone1** [wonipapa/epg2xml#93]
항상 감사합니다.

프로그램 제목에 "<", ">" 문자가 포함되어 있을 경우, 해당 프로가 누락되거나 제목이 올바로 표출되지 않는 문제가 있습니다.

샘플 채널 : SKB - Discovery Channel (Service ID : 51)

**Comment by wonipapa** [comment]
원인 파악해보겠습니다.

**Comment by wonipapa** [comment]
수정했습니다.
