### ISSUE TITLE
채널 ID 457 플레이런TV 데이터를 못가져 오네요.

### ISSUE THREAD

**Issue by ParkSeongGyu** [wonipapa/epg2xml#94]
감사히 잘 사용하고 있습니다.

**ID 457 플레이런TV** 의 EPG가 2달 전부터 가져오지 못 하네요.
여유 되실 때 확인 부탁드립니다.

저는 **Btv** 사용 중입니다.

**Comment by wonipapa** [comment]
플레이런TV가 소스가 LG인데 LG쪽에서 정보 제공을 안하고 있었네요.
소스를 변경하도로고 하겠습니다. Channel.json에 새로 반영해서 올려놓도록 하겠습니다.
