### ISSUE TITLE
SKY epg주소가 막힌듯 하네요

### ISSUE THREAD

**Issue by yc-cats** [wonipapa/epg2xml#96]
http://www.skylife.co.kr/channel/epg/channelScheduleListJson.do

404에러 나옵니다.

지상파 모두 못불러오네요

일단 Channel.json에서 SKY를 EPG로 변경하니 가져오긴 합니다.

**Comment by wjdtncjs** [comment]
수고를 덜어드리고 싶어서 찾아 봤습니다.
function GetEPGFromSKY($ChannelInfo) {
    $ChannelId = $ChannelInfo[0];
    $ChannelName = $ChannelInfo[1];
    $ServiceId =  $ChannelInfo[3];
    foreach(range(1, $GLOBALS['period']) as $k) :
        $url = "http://www.skylife.co.kr/channel/epg/channelScheduleListJson.do";
                   :
                   :
주소가 변경되었습니다.
http://www.skylife.co.kr/channel/epg/channelScheduleListJson.do
->
http://www.skylife.co.kr/channel/**epglist**/channelScheduleListJson.do

저 주소만 아래걸로 수정하시면 가져올거에요~

**Comment by wonipapa** [comment]
수정완료
