### ISSUE TITLE
소스가 HCN으로 되어 있는 채널들의 프로그램이 안 들어오는 듯 합니다.

### ISSUE THREAD

**Issue by justinus-choo** [wonipapa/epg2xml#99]
제목대로 Channel.json 파일에 소스가 HCN으로 되어 있는 채널들의 프로그램 목록이 안들어오고 있습니다.
확인 부탁드립니다.

Channel.json을 보면 채널별로 정보를 받아오는 소스가 다른 것으로 보이는데요.
어떤 기준으로 나눠 놓으신 건지 궁금합니다.
사용하다 보면 특정 소스의 채널들만 안되는 경우가 종종 생기는 것 같은데,
채널별로 여러 소스 중 선택해서 받아올 수 있도록 해 주시면 어떨까 하는 생각도 들고요..
이에 대한 의견은 어떠신지요 ^^

**Comment by mysoun** [comment]
HCN 쪽에서 에러가 발생하고있습니다.
Warning: DOMDocument::loadHTML(): Empty string supplied as input in /share/CACHEDEV1_DATA/.qpkg/Entware-ng/etc/epg2xml/epg2xml-web.php on line 1066

이런 에러가 나고있네요.

**Comment by wonipapa** [comment]
HCN에서 막아서 그렇습니다.
함수를 조금 수정해서 가능하게는 했는데 Channel.json 수정으로 가는 게 낳을 것 같습니다.

**Comment by wonipapa** [comment]
Channel.json 기준은 제가 임의로 하는 겁니다.
부하 분산의 목적입니다.
여러소스를 선택하는 건 고민해봤는데 고려해야할 게 많아서 아직은 미정입니다.
